source("scripts/modelos.R")

modelo.cax <- lm(data = cax, Quantity ~ Sample)
modelo.rub <- lm(data = rub, Quantity ~ Sample)
modelo.sar <- lm(data = sar, Quantity ~ Sample)

summary(modelo.cax)
summary(modelo.rub)
summary(modelo.sar)

par(mfrow = c(2,2))
plot(modelo.cax)
plot(modelo.rub)
plot(modelo.sar)

png("teste.png", 900,400)
par(mfrow = c(1,3))
with(cax, boxplot(Quantity ~ Sample))
title(sub = "CAX")
with(rub, boxplot(Quantity ~ Sample))
title(sub = "RUB")
with(sar, boxplot(Quantity ~ Sample))
title(sub = "SAR")
dev.off()

png("teste2.png", 900, 400)
par(mfrow = c(1,3))
with(cax[Sample == "vacina liofilizada"], hist(Quantity))
title(sub = "CAX lio")
with(rub[Sample == "vacina formulada"], hist(Quantity))
title(sub = "RUB form")
with(sar[Sample == "vacina formulada"], hist(Quantity))
title(sub = "SAR form")
dev.off()

png("teste3.png", 900, 900)
par(mfrow = c(3,3))
with(cax, by(Quantity, Sample, function(x) {qqnorm(x, main = "CAX"); qqline(x)}))
with(rub, by(Quantity, Sample, function(x) {qqnorm(x, main = "RUB"); qqline(x)}))
with(sar, by(Quantity, Sample, function(x) {qqnorm(x, main = "SAR"); qqline(x)}))
dev.off()
